### ISSUE TITLE
Install fails: No module named 'pybind11'

### ISSUE THREAD

**Issue by Mineru98** [hyunwoongko/python-mecab-kor#1]
## Summary

pip 설치시 아래와 같이 에러가 발생 되면서 설치가 안됩니다.

하지만 python-mecab-kor 레포를 clone 후 `python setup.py`를 통해서는 설치가 잘 됩니다.

## System
```
Python 3.9
Pip 22.0.4
OS : Monterey 12.3
CPU architecture : arm64
```

---

```bash
$ pip install python-mecab-kor
```

> Building wheels for collected packages: python-mecab-kor
  Building wheel for python-mecab-kor (setup.py) ... error
  error: subprocess-exited-with-error
> 
> × python setup.py bdist_wheel did not run successfully.
> clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -I/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c /var/folders/cx/d_vzh8vd4_vd__73170fz7qc0000gn/T/tmpg89udury.cpp -o var/folders/cx/d_vzh8vd4_vd__73170fz7qc0000gn/T/tmpg89udury.o -std=c++14
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -I/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c /var/folders/cx/d_vzh8vd4_vd__73170fz7qc0000gn/T/tmp1apf8l4i.cpp -o var/folders/cx/d_vzh8vd4_vd__73170fz7qc0000gn/T/tmp1apf8l4i.o -fvisibility=hidden
      building '_mecab' extension
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/cx/d_vzh8vd4_vd__73170fz7qc0000gn/T/pip-install-8g8j8ytt/python-mecab-kor_b1a1ca715a85434c96fd734449da3b69/setup.py", line 155, in <module>
          setup(
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/opt/homebrew/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
          self.build_extensions()
        File "/private/var/folders/cx/d_vzh8vd4_vd__73170fz7qc0000gn/T/pip-install-8g8j8ytt/python-mecab-kor_b1a1ca715a85434c96fd734449da3b69/setup.py", line 61, in build_extensions
          super().build_extensions()
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
          self._build_extensions_serial()
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
          self.build_extension(ext)
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
          _build_ext.build_extension(self, ext)
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 528, in build_extension
          objects = self.compiler.compile(sources,
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/ccompiler.py", line 565, in compile
          self._setup_compile(output_dir, macros, include_dirs, sources,
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/ccompiler.py", line 341, in _setup_compile
          pp_opts = gen_preprocess_options(macros, incdirs)
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/ccompiler.py", line 1083, in gen_preprocess_options
          pp_opts.append("-I%s" % dir)
        File "/private/var/folders/cx/d_vzh8vd4_vd__73170fz7qc0000gn/T/pip-install-8g8j8ytt/python-mecab-kor_b1a1ca715a85434c96fd734449da3b69/setup.py", line 113, in __str__
          return func(*self.args, **self.kwargs)
        File "/private/var/folders/cx/d_vzh8vd4_vd__73170fz7qc0000gn/T/pip-install-8g8j8ytt/python-mecab-kor_b1a1ca715a85434c96fd734449da3b69/setup.py", line 126, in get_pybind_include
          import pybind11
      ModuleNotFoundError: No module named 'pybind11'

**Comment by hyunwoongko** [comment]
1.1.6으로 올렸는데 다시 해보시겠어요?
`pip install python-mecab-kor==1.1.6`

**Comment by hyunwoongko** [comment]
신텍스 관련 버그는 1.1.7에서 해결.

**Comment by Mineru98** [comment]
```bash
$ pip installl python-mecab-kor==1.1.6
```
---
> Running setup.py install for python-mecab-kor ... error
  error: subprocess-exited-with-error
> 
> **ERROR: Invalid requirement: '~='**
> Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/cx/d_vzh8vd4_vd__73170fz7qc0000gn/T/pip-install-fkh3epf3/python-mecab-kor_0fe718429e7e4fc2b4c208d208fe99a7/setup.py", line 155, in <module>
          setup(
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/private/var/folders/cx/d_vzh8vd4_vd__73170fz7qc0000gn/T/pip-install-fkh3epf3/python-mecab-kor_0fe718429e7e4fc2b4c208d208fe99a7/setup.py", line 103, in run
          super().run()
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/command/install.py", line 670, in run
          self.run_command('build')
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/opt/homebrew/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/private/var/folders/cx/d_vzh8vd4_vd__73170fz7qc0000gn/T/pip-install-fkh3epf3/python-mecab-kor_0fe718429e7e4fc2b4c208d208fe99a7/setup.py", line 23, in run
          subprocess.check_call(
        File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command 'sh /private/var/folders/cx/d_vzh8vd4_vd__73170fz7qc0000gn/T/pip-install-fkh3epf3/python-mecab-kor_0fe718429e7e4fc2b4c208d208fe99a7/scripts/install_requirements.sh'
> **returned non-zero exit status 1**

**Comment by Mineru98** [comment]
[install_requirements.sh](https://github.com/hyunwoongko/python-mecab-kor/blob/main/scripts/install_requirements.sh)에서 오타로 인해서 문제가 발생했는데 1.1.7에서 해당 설치 이슈는 해결 되었습니다.

**Comment by waky80** [comment]
`$ pip install pybind11`
`$ CFLAGS="$(python -m pybind11 --includes)" pip install python-mecab-kor`
