### ISSUE TITLE
[poetry error] pybind11 module not found

### ISSUE THREAD

**Issue by gigio1023** [hyunwoongko/python-mecab-kor#5]
- Platform: Mac OS
- Python: 3.11.3, conda env
- Environment:  
  - 에러 재현을 위해 빈 디렉터리에서 poetry init 후, 모두 default configuration으로 기록. 
  - PEP-517을 지원하는 poetry.core 사용, https://python-poetry.org/docs/pyproject/#poetry-and-pep-517.   
  - pip로는 설치되는 것 확인. 

------

- conda로 env 생성 후 poetry로 설치 진행 시 아래와 같은 에러가 발생합니다. pybind11 패키지 설치 후에도 동일한 문제가 있습니다.
- pip wheel --use-pep517 "python-mecab-kor (==1.2.8)" 수행 후에도 동일한 에러가 재현됩니다.

```sh
(poetry_test) ➜  poetry add pybind11
Configuration file exists at /Users/mac/Library/Preferences/pypoetry, reusing this directory.

Consider moving TOML configuration files to /Users/mac/Library/Application Support/pypoetry, as support for the legacy directory will be removed in an upcoming release.
Using version ^2.10.4 for pybind11

Updating dependencies
Resolving dependencies... (0.1s)

Package operations: 1 install, 0 updates, 0 removals

  • Installing pybind11 (2.10.4)

Writing lock file
(poetry_test) ➜  poetry add python-mecab-kor
Configuration file exists at /Users/mac/Library/Preferences/pypoetry, reusing this directory.

Consider moving TOML configuration files to /Users/mac/Library/Application Support/pypoetry, as support for the legacy directory will be removed in an upcoming release.
Using version ^1.2.8 for python-mecab-kor

Updating dependencies
Resolving dependencies... (0.1s)

Package operations: 1 install, 0 updates, 0 removals

  • Installing python-mecab-kor (1.2.8): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel

  running bdist_wheel
  running build
  running build_py
  Warning: curl 8.1.2_1 is already installed and up-to-date.
  To reinstall 8.1.2_1, run:
    brew reinstall curl
  Warning: git 2.41.0_1 is already installed and up-to-date.
  To reinstall 2.41.0_1, run:
    brew reinstall git
  creating build
  creating build/lib.macosx-11.1-arm64-cpython-311
  creating build/lib.macosx-11.1-arm64-cpython-311/mecab
  copying mecab/mecab.py -> build/lib.macosx-11.1-arm64-cpython-311/mecab
  copying mecab/__init__.py -> build/lib.macosx-11.1-arm64-cpython-311/mecab
  running build_ext
  creating var
  creating var/folders
  creating var/folders/z0
  creating var/folders/z0/c853x2d154sf2bwrknp1svxr0000gn
  creating var/folders/z0/c853x2d154sf2bwrknp1svxr0000gn/T
  clang -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/mac/miniconda3/envs/poetry_test/include -arch arm64 -fPIC -O2 -isystem /Users/mac/miniconda3/envs/poetry_test/include -arch arm64 -I/var/folders/z0/c853x2d154sf2bwrknp1svxr0000gn/T/tmpcfw98pi3/.venv/include -I/Users/mac/miniconda3/envs/poetry_test/include/python3.11 -c /var/folders/z0/c853x2d154sf2bwrknp1svxr0000gn/T/tmpss7zr48d.cpp -o var/folders/z0/c853x2d154sf2bwrknp1svxr0000gn/T/tmpss7zr48d.o -std=c++14
  clang -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/mac/miniconda3/envs/poetry_test/include -arch arm64 -fPIC -O2 -isystem /Users/mac/miniconda3/envs/poetry_test/include -arch arm64 -I/var/folders/z0/c853x2d154sf2bwrknp1svxr0000gn/T/tmpcfw98pi3/.venv/include -I/Users/mac/miniconda3/envs/poetry_test/include/python3.11 -c /var/folders/z0/c853x2d154sf2bwrknp1svxr0000gn/T/tmpwgj08ifb.cpp -o var/folders/z0/c853x2d154sf2bwrknp1svxr0000gn/T/tmpwgj08ifb.o -fvisibility=hidden
  building '_mecab' extension
  Traceback (most recent call last):
    File "/Users/mac/miniconda3/envs/poetry_test/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/Users/mac/miniconda3/envs/poetry_test/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/mac/miniconda3/envs/poetry_test/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/var/folders/z0/c853x2d154sf2bwrknp1svxr0000gn/T/tmpcfw98pi3/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 416, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/var/folders/z0/c853x2d154sf2bwrknp1svxr0000gn/T/tmpcfw98pi3/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 401, in _build_with_temp_dir
      self.run_setup()
    File "/var/folders/z0/c853x2d154sf2bwrknp1svxr0000gn/T/tmpcfw98pi3/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 488, in run_setup
      self).run_setup(setup_script=setup_script)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/var/folders/z0/c853x2d154sf2bwrknp1svxr0000gn/T/tmpcfw98pi3/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
      exec(code, locals())
    File "<string>", line 179, in <module>
    File "/var/folders/z0/c853x2d154sf2bwrknp1svxr0000gn/T/tmpcfw98pi3/.venv/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
      return distutils.core.setup(**attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/var/folders/z0/c853x2d154sf2bwrknp1svxr0000gn/T/tmpcfw98pi3/.venv/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
             ^^^^^^^^^^^^^^^^^^
    File "/var/folders/z0/c853x2d154sf2bwrknp1svxr0000gn/T/tmpcfw98pi3/.venv/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
    File "/var/folders/z0/c853x2d154sf2bwrknp1svxr0000gn/T/tmpcfw98pi3/.venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "/var/folders/z0/c853x2d154sf2bwrknp1svxr0000gn/T/tmpcfw98pi3/.venv/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
      super().run_command(command)
    File "/var/folders/z0/c853x2d154sf2bwrknp1svxr0000gn/T/tmpcfw98pi3/.venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/var/folders/z0/c853x2d154sf2bwrknp1svxr0000gn/T/tmpcfw98pi3/.venv/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 343, in run
      self.run_command("build")
    File "/var/folders/z0/c853x2d154sf2bwrknp1svxr0000gn/T/tmpcfw98pi3/.venv/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "/var/folders/z0/c853x2d154sf2bwrknp1svxr0000gn/T/tmpcfw98pi3/.venv/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
      super().run_command(command)
    File "/var/folders/z0/c853x2d154sf2bwrknp1svxr0000gn/T/tmpcfw98pi3/.venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/var/folders/z0/c853x2d154sf2bwrknp1svxr0000gn/T/tmpcfw98pi3/.venv/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run
      self.run_command(cmd_name)
    File "/var/folders/z0/c853x2d154sf2bwrknp1svxr0000gn/T/tmpcfw98pi3/.venv/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
      self.distribution.run_command(command)
    File "/var/folders/z0/c853x2d154sf2bwrknp1svxr0000gn/T/tmpcfw98pi3/.venv/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
      super().run_command(command)
    File "/var/folders/z0/c853x2d154sf2bwrknp1svxr0000gn/T/tmpcfw98pi3/.venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/var/folders/z0/c853x2d154sf2bwrknp1svxr0000gn/T/tmpcfw98pi3/.venv/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 84, in run
      _build_ext.run(self)
    File "/var/folders/z0/c853x2d154sf2bwrknp1svxr0000gn/T/tmpcfw98pi3/.venv/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
      self.build_extensions()
    File "<string>", line 50, in build_extensions
    File "/var/folders/z0/c853x2d154sf2bwrknp1svxr0000gn/T/tmpcfw98pi3/.venv/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
      self._build_extensions_serial()
    File "/var/folders/z0/c853x2d154sf2bwrknp1svxr0000gn/T/tmpcfw98pi3/.venv/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
      self.build_extension(ext)
    File "/var/folders/z0/c853x2d154sf2bwrknp1svxr0000gn/T/tmpcfw98pi3/.venv/lib/python3.11/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
      _build_ext.build_extension(self, ext)
    File "/var/folders/z0/c853x2d154sf2bwrknp1svxr0000gn/T/tmpcfw98pi3/.venv/lib/python3.11/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
      objects = self.compiler.compile(
                ^^^^^^^^^^^^^^^^^^^^^^
    File "/var/folders/z0/c853x2d154sf2bwrknp1svxr0000gn/T/tmpcfw98pi3/.venv/lib/python3.11/site-packages/setuptools/_distutils/ccompiler.py", line 590, in compile
      macros, objects, extra_postargs, pp_opts, build = self._setup_compile(
                                                        ^^^^^^^^^^^^^^^^^^^^
    File "/var/folders/z0/c853x2d154sf2bwrknp1svxr0000gn/T/tmpcfw98pi3/.venv/lib/python3.11/site-packages/setuptools/_distutils/ccompiler.py", line 348, in _setup_compile
      pp_opts = gen_preprocess_options(macros, incdirs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/var/folders/z0/c853x2d154sf2bwrknp1svxr0000gn/T/tmpcfw98pi3/.venv/lib/python3.11/site-packages/setuptools/_distutils/ccompiler.py", line 1213, in gen_preprocess_options
      pp_opts.append("-I%s" % dir)
                     ~~~~~~~^~~~~
    File "<string>", line 134, in __str__
    File "<string>", line 149, in get_pybind_include
  ModuleNotFoundError: No module named 'pybind11'


  at ~/miniconda3/envs/poetry_test/lib/python3.11/site-packages/poetry/installation/chef.py:147 in _prepare
      143│
      144│                 error = ChefBuildError("\n\n".join(message_parts))
      145│
      146│             if error is not None:
    → 147│                 raise error from None
      148│
      149│             return path
      150│
      151│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with python-mecab-kor (1.2.8) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "python-mecab-kor (==1.2.8)"'.

```

**Comment by waky80** [comment]
MacOS
```
$ pip install pybind11
$ CFLAGS="$(python -m pybind11 --includes)" pip install python-mecab-kor
```

Ubuntu
`$ uv add python-mecab-kor --no-build-isolation`
